agent_type: neural_boltzmann
study:
  directions: ['maximize']
  sampler:
    _target_: optuna.samplers.TPESampler
n_trial: 12
n_job_in_parallel: 2
n_instance_per_trial: 3
n_eval_trajectories: 10
consider_past_trials: True
sleep_time: 600 # seconds
params:
  'optimizer.learning_rate':
    type: 'float' # categorical or float or int
    low: 0.001
    high: 0.05
  'context_features':
    type: 'categorical' # categorical or float or int
    value: [[
      'avg_purchase_price', 
      'avg_purchase_quantity', 
      'avg_purchase_probability', 
      'avg_redeemed_discount', 
      'avg_purchase_discount', 
      'previous_transaction',
      'product_price', 
      'marketing_feature',
      'observed_customer_product_feature',
      ],
    ]
  'temperature':
    type: 'float' # categorical or float or int
    low: 0.1
    high: 0.9
  'hidden_layers':
    type: 'categorical'
    value: [[8, 2], [16, 4], [32, 8]]
batch_job_train:
  job_name: ${optuna.agent_type}_parameter_tuning
  job_queue: "experiment_workflow"
  job_definition: "parameter_tuning"
  command: ["python", "workflow/optuna_job.py", "step=train", "synthetic_data=${synthetic_data.name}", "pyenv=${pyenv.name}"]
  memory: '100000' # need to be string format
  vcpus: '4' # need to be string format
  timeout: 72000 # seconds
batch_job_eval:
  job_name: ${optuna.agent_type}_parameter_tuning_eval
  job_queue: "experiment_workflow"
  job_definition: "parameter_tuning"
  command: ["python", "workflow/optuna_job.py", "step=eval", "synthetic_data=${synthetic_data.name}", "pyenv=${pyenv.name}"]
  memory: '10000' # need to be string format
  vcpus: '2' # need to be string format
  timeout: 72000 # seconds